spring.application.name=JavaWebExam_ntsang
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/pet_boarding_ntsang?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.training.javaweb.exam=DEBUG
logging.level.org.mybatis=DEBUG
logging.level.org.springframework.security=INFO